### ISSUE TITLE
Mob Battle Incompatibility

### ISSUE THREAD

**Issue by Bastian-Fernandez-Cortez** [bglandolt/bettercombat#11]
v 8-18-2023

Adding "mobbattle:mob_stick" to the Blacklisted items in the config does not allow the Mob Enrager item from the Mob Battle (v 2.3.4) mod to work properly.

I even created a modpack with only those two mods to make sure that no other mods were the cause of the Mob Enrager not working.

**Comment by ANormalRaft** [comment]
(Same person, different account) Still doesn't work on v 9-2-2023 
(Though this time I didn't create a different modpack to test)

**Comment by bglandolt** [comment]
No plans to support Mob Battle
