### ISSUE TITLE
Can no longer break Quark totem of holding in latest version

### ISSUE THREAD

**Issue by CalaMariGold** [bglandolt/bettercombat#14]
Not sure what changed with the recent Immersive Combat updates but I can't collect my items in Quark's totem of holding anymore. Removing immersive combat fixed the issue.

**Comment by bglandolt** [comment]
How does the totem work, do you have to left click to attack and break it? Or right click it?

**Comment by bglandolt** [comment]
This should be fixed, feel free to @ me in the discord if not
