### ISSUE TITLE
Offhand animation do not work with taoism mod

### ISSUE THREAD

**Issue by HuangAdam** [bglandolt/bettercombat#17]
If I don't change Taoism setting, the offhand animation is working.
If I change setting like this
```
    S:combatItems <
        example:sword, 3.5, 1.5, false
        example:shield, 0.3, 0.6, true
        minecraft:wooden_sword, 3, 2, false
        minecraft:stone_sword, 3, 2, false
     >
```
The animation will not work when the offhand weapon is wood sword or stone sword.

Nothing in log
Mod version: 10-25
Forge version: 14.23.5.2860

**Comment by bglandolt** [comment]
Taoism mod not supported, the only weapon/combat mod that is currently supported is Spartan Weaponry due to popularity
