### ISSUE TITLE
Throwing weapons from spartan weapons behaving oddly

### ISSUE THREAD

**Issue by sneetsnart** [bglandolt/bettercombat#20]
when you throw a throwing weapon from spartan weaponry that has the returning enchantment, if you are holding right click when it returns it will shoot out another projectile immediately

**Comment by bglandolt** [comment]
This should be fixed in the latest update (3/20)

If not, please reopen

I have tested this in a server too - do note that the throwing weapon may play a re-equip animation after the projectile has returned - this is just visual and another projectile does not actually shoot
