### ISSUE TITLE
Extra Attack Height and Width don't work

### ISSUE THREAD

**Issue by CalaMariGold** [bglandolt/bettercombat#21]
![image](https://github.com/bglandolt/bettercombat/assets/57605926/9f0a633e-39ae-4264-9d17-0ff7b2aaf369)

These 2 options here dont seem to do anything. Width at 1.0 and attacking mobs with a sword just a couple pixels away from their main hitbox doesn't hit them.

**Comment by bglandolt** [comment]
Yes I did notice this too, next update will have this fixed

**Comment by democat3457** [comment]
@bglandolt can you commit and push that change? gonna see if i can fix any of the other bugs as well
