### ISSUE TITLE
Larger reach values not working at all & Offhand weapons can't auto attack

### ISSUE THREAD

**Issue by evilchin** [bglandolt/bettercombat#24]
It seems that the reach attribute for weapons is currently not applying at all. Any defined weapon with a reach value higher than the default, caps back down. But weapons that are capped below default seem to work fine (like daggers). This issue seems to have popped up after the release of the 12/18/2023 build of the mod, as prior versions don't have this issue. This issue may be related to #23 , but I'm not 100% sure so I just figured it'd be easier to file this as a separate issue.

Another small gripe is that you can't auto attack with your offhand since 12/18/2023 build as well. So you can't hold right click to automatically attack with your offhand weapon.

Both these issues were tested on the 12/18/23 and 12/20/23 versions, with no other mods. These issues are absent on the 10/25/2023 build of the mod for context. If you need anymore context or testing, let me know.

**Comment by bglandolt** [comment]
Reach fixed in latest 3/20 update
Hold offhand to auto-attack fixed in latest 3/20 update
