### ISSUE TITLE
Auto Attack

### ISSUE THREAD

**Issue by fzrdwa123456** [bglandolt/bettercombat#25]
https://github.com/bglandolt/bettercombat/assets/130232431/2ffae254-362c-4926-b2f4-236f25a0cb05

Are you compatible with the 'Modern Warfare Cubed' mod?

This is a link to "https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed"

**Comment by bglandolt** [comment]
Try adding

com.paneedah.weaponlib.Weapon

to the **(Class) Item Blacklist** in the config

**Comment by fzrdwa123456** [comment]
> Try adding
> 
> com.paneedah.weaponlib.Weapon
> 
> to the **(Class) Item Blacklist** in the config

I tried and it didn't work

**Comment by bglandolt** [comment]
actually, use this instead:

com.paneedah.mwc.weapons.Guns

instead of com.paneedah.weaponlib.Weapon
