### ISSUE TITLE
I can't attack a dummy

### ISSUE THREAD

**Issue by fzrdwa123456** [bglandolt/bettercombat#26]
https://github.com/bglandolt/bettercombat/assets/130232431/3bfeb786-cbd1-43bd-b692-94ee52c1fce6

mod link "https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm" MmmMmmMmmMmm (Target Dummy)

**Comment by bglandolt** [comment]
https://github.com/bglandolt/bettercombat/issues/12
