### ISSUE TITLE
Thaumcraft "Arcing" effect not working

### ISSUE THREAD

**Issue by boniblade** [bglandolt/bettercombat#27]
The infusion enchantment from Thaumcraft named "Arcing" is non-functional for weapons that work with Immersive Combat.
"Arcing" makes the weapon chain-attack other enemies from it's point of impact, looking like gusts of wind.

The enchantment can be tested ingame using the Sword of the Zephyr, which comes with the enchantment on it's own,
-though it can be applied to other weapons aswell, which is why I am making this issue; I would like to use "Arcing"-!

Your response and solution would be really really appreciated!

![2024-03-31_13 33 20](https://github.com/bglandolt/bettercombat/assets/41778816/68ed43e5-57ee-4e6d-b417-81289cbd7795)
In this image, only the zombie and the horse are damaged; the others are not hit, despite the weapon having "Arcing".

**Comment by bglandolt** [comment]
Unfortunately Thaumcraft does not have its source code available so I cannot see what is causing this issue and I am unable to fix it

**Comment by bglandolt** [comment]
Unfortunately Thaumcraft does not have its source code available so I cannot see what is causing this issue and I am unable to fix it
