### ISSUE TITLE
[v6-27-2023] Strange behaviors when right-cliking with blocks

### ISSUE THREAD

**Issue by Vetpetmon** [bglandolt/bettercombat#3]
Just updated to fix the dedicated server crash, and there's more problems:

Right clicking doors with a block causes the door to open and close in the same tick
Holding down right click does not continue to place blocks.

**Comment by Vetpetmon** [comment]
Confirmed this is the mod causing the issue; removed it from my server and block placements and door usage is back to vanilla behaviors.

**Comment by bglandolt** [comment]
Fixed in latest version
