### ISSUE TITLE
Option to disable new animations

### ISSUE THREAD

**Issue by darchitectlp** [bglandolt/bettercombat#30]
Besides creating new tool and weapon animations, it looks like this mod adds a lot of other capabilities to combat, which is GREAT. Unfortunately, some of the animations are visually overwhelming or super distracting. After mining for a bit, the constant animation of the pickaxe flying back at my screen became very distracting. Not great for people watching streams, either.

Is it possible to have a setting that just uses default animations for tool use, but allows all the other great things this mod does? or is there an option to greatly reduce the motion of the animation? Right now, I feel it is just too much. Thanks!

**Comment by bglandolt** [comment]
mining animation has been reduced / changed so it is less distracting
