### ISSUE TITLE
Axe tweaker not working / Axes dont disable shields

### ISSUE THREAD

**Issue by HMSMarengo** [bglandolt/bettercombat#35]
Custom weapons added in axe substring dont disable vanila and modded shields.

Testing with ancientwarfare halberds, better survival battleaxes and epic knights weapons.

**Comment by bglandolt** [comment]
Can you show me your config and how are you testing on shields? Is it against mobs or players in multiplayer?

**Comment by HMSMarengo** [comment]
[bettercombat.txt](https://github.com/bglandolt/bettercombat/files/15233161/bettercombat.txt)

**Comment by HMSMarengo** [comment]
Tested with vanilla mob like zombie, ancientwarfare npc and with my friend on local server

**Comment by bglandolt** [comment]
the modid is not ancientwarfarenpc, it is just ancientwarfare

[Axe Substring=ancientwarfarenpc:wooden_halberd]

should be

[Axe Substring=ancientwarfare:wooden_halberd]
