### ISSUE TITLE
Immersive Combat & Mo' Bends & Real First Person

### ISSUE THREAD

**Issue by al-wei** [bglandolt/bettercombat#36]
Can you make the animation work to Mo' Bends? Can see the action in the first person. Immersive Combat animation can be seen in the first person.

![2024-06-09_14 37 22](https://github.com/bglandolt/immersivecombat/assets/145486869/df8b76e9-adb5-4291-bbb9-7dd82240231c)
![2024-06-09_14 37 35](https://github.com/bglandolt/immersivecombat/assets/145486869/e8c3a262-1785-40bd-b9ce-ea1caf22d22d)

**Comment by bglandolt** [comment]
I do not understand what you are saying

**Comment by al-wei** [comment]
> I do not understand what you are saying

Animation that applies to (Mo' Bends).
The real first person mod can see the bettercombat animation.

**Comment by al-wei** [comment]
Mo' Bends battle animation

**Comment by bglandolt** [comment]
Remove one of those mods, using all 3 will lead to issues like this.

Real First Person mod and Immersive Combat cannot really go together, so you will have to pick and choose
