### ISSUE TITLE
Substring not recognising weapons

### ISSUE THREAD

**Issue by LuciferWPF910** [bglandolt/bettercombat#42]
Hello,

I'm using mods that have flat ideas with no seperations.
For example - cinderextras2:anubisdagger-
When setting the substring to simply "dagger" it will not recognise the weapon as a dagger.
Even when the substring is the full id without resource location "anubisdagger" it still doesn't recognise it.

I'm unsure whether this is a fault in my understanding or a potential issue with how it reads the substring.
I'd love to suggest the ability to simply use resource locations as well as substrings, like in other parts of the code.

**Comment by Xvareon** [comment]
The anubis dagger probably isnt extended from sword or axe classes so its not being detected as a weapon

**Comment by LuciferWPF910** [comment]
It is, I wrote the code for the mod and I have tried all other methods within the provided mod itself.

**Comment by Xvareon** [comment]
I see, if its extending from sword or axe classes, does the default knockback and critical chance show? meaning the mod recognizes it as a sword or axe. If it does, did you try to put the anubis dagger at the very front of the custom tweaker list in the configs?

**Comment by LuciferWPF910** [comment]
I think a solution to this problem is just adding a feature to directly add specific weapons to a certain type.
via modid:item_name
