### ISSUE TITLE
My server kicks me out each time a bleed event occurs

### ISSUE THREAD

**Issue by Xvareon** [bglandolt/bettercombat#48]
I will paste the relevant server log here (its recurring as well):
[message.txt](https://github.com/user-attachments/files/16799598/message.txt)

**Comment by Xvareon** [comment]
To reproduce:
Hit a mob with a weapon that inflicts bleed upon critical strike.

This can only be reproduced consistently when playing on a server. I don't seem to get this issue on single player.

**Comment by bglandolt** [comment]
Should be fixed in the 9/10 update
