### ISSUE TITLE
Unsheath speed mistakenly uses last selected item

### ISSUE THREAD

**Issue by jagprog7** [bglandolt/bettercombat#49]
Version: `ImmersiveCombat-4-25-2024.jar`

To reproduce, get a slow weapon in your hotbar. For example, run this in a command block:

`/give @p minecraft:wooden_axe 1 10000 {AttributeModifiers:[{Slot:"mainhand",AttributeName:generic.attackSpeed,Name:generic.attackSpeed,Amount:-3.95,Operation:0,UUIDLeast:-590699294,UUIDMost:-871380948}],display:{Name:"Lesser Boom Axe",Lore:["Annihilates itself after one use"]},ench:[{id:16,lvl:50},{id:19,lvl:5},{id:51,lvl:1}]}`

Swap over to it. It will take around 20 seconds to unsheath.

During this 20 seconds, swap to anything else. For example, empty hand. It will have inherited this long duration. The item will also take a long time to unsheath. It uses the duration from the previous weapon when using the new weapon.

Please let me know if this is intentional. If it is, I would request a config to not have it like this. Thanks.

**Comment by bglandolt** [comment]
This should be fixed in the 9/10 update, let me know if this still happens
