### ISSUE TITLE
Null Pointer Exception when attacking an entity that is an instance of `IEntityOwnable`

### ISSUE THREAD

**Issue by thakyZ** [bglandolt/bettercombat#7]
I am submitting this bug report on behalf of a friend. They attacked a dragon on a custom modpack and a it crashed with a null pointer exception.
Here is the log file:
<https://gist.github.com/thakyZ/70b10392e5c53674b267b6c7ed2db680>

The crash happens around the line `1122` of [src/main/java/bettercombat/mod/util/ConfigurationHandler.java](https://github.com/bglandolt/bettercombat/blob/main/src/main/java/bettercombat/mod/util/ConfigurationHandler.java)
Where it currently reads something like on the latest build on Curseforge:
```java
if (entity instanceof IEntityOwnable && ((IEntityOwnable)entity).func_70902_q().equals(player))
```

**Comment by bglandolt** [comment]
fixed in ImmersiveCombat-8-18-2023
