### ISSUE TITLE
Nullpointer crash when attacking with a shovel

### ISSUE THREAD

**Issue by CalaMariGold** [bglandolt/bettercombat#9]
I'm not sure what exactly caused it except that i was attacking with a shovel.

https://mclo.gs/7jpBasN

**Comment by ANormalRaft** [comment]
While doing some testing of my own, I found out that removing ReachFix (which was a leftover from a mod I removed) stopped the shovel and hoes related crashes

**Comment by bglandolt** [comment]
Should be fixed with today's update
